name: Deploy EC2

on:
  push:
    branches: [ main ]

env:
  EC2_USER: 'ec2-user'
  EC2_HOST: 43.207.212.203
  DEST_JAR_NAME: 'todo.jar'
  DEST_PATH: '/home/ec2-user'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Copy jar to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/todo-0.0.1-SNAPSHOT.jar ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.DEST_PATH }}/${{ env.DEST_JAR_NAME }}
          rm private_key.pem

      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            echo "Stopping existing app (if any)..."
            PID=$(ps aux | grep 'todo.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              echo "Found running app with PID: $PID. Stopping it..."
              kill -9 $PID
              sleep 3
            else
              echo "No running app found."
            fi
            
            echo "Checking files..."
            ls -la /home/ec2-user/*.jar
            
            echo "Starting new app with database config..."
            nohup java -jar /home/ec2-user/todo.jar \
              --server.port=8080 \
              --spring.datasource.url="${{ secrets.DB_URL }}" \
              --spring.datasource.username="${{ secrets.DB_USERNAME }}" \
              --spring.datasource.password="${{ secrets.DB_PASSWORD }}" \
              > /home/ec2-user/app.log 2>&1 &
            
            sleep 5
            echo "Checking if app started..."
            if ps aux | grep 'todo.jar' | grep -v grep > /dev/null; then
              echo "App started successfully!"
              echo "Recent logs:"
              tail -5 /home/ec2-user/app.log
            else
              echo "App failed to start. Error logs:"
              tail -10 /home/ec2-user/app.log
            fi
